### ISSUE TITLE
NYT-FB

### ISSUE THREAD

**Issue by HUSTLyn** [thunlp/OHRE#2]

**Comment by HUSTLyn** [comment]
I contacted Diego and got the dataset, but I am still confused about what to do with the original NYT-FB dataset.
Could you provide the code of process the NYT-FB dataset please?

**Comment by drogozhang** [comment]
Hi, thanks for your interests. We borrow the processed NYT-FB dataset from RSN(https://github.com/thunlp/RSN).

**Comment by HUSTLyn** [comment]
As far as I know, RSN did not use the NYT-FB dataset in the experiment. 0.0

**Comment by drogozhang** [comment]
Sorry, I got it wrong. 
Could you kindly tell me an email address so that I can send you the processed NYT-FB dataset.

**Comment by HUSTLyn** [comment]
> Sorry, I got it wrong.
> Could you kindly leave your email address so that I can send your the processed nyt-fb file via email.

Thank you so much!
My email address is: liyn20@mails.tsinghua.edu.cn

**Comment by ChunhuaLiu596** [comment]
Hi, 
Very interesting paper! I got the data from Diego as well. And wanted to run the code. Could you please also share me a copy of the processed nyt-fb data? 
My email address is: chunhua@student.unimelb.edu.au  

Many thanks in advance!
